language: php

php:
  - 7.4

install:
  - composer install --dev

script:
  - ./vendor/bin/phpstan
  - ./vendor/bin/phpstan analyze -l 8 src
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpunit --testsuite=integration

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS dqo;'
  - psql -c 'create database dqo;' -U postgres

env:
    global:
        - POSTGRES_HOST=127.0.0.1
        - POSTGRES_USER=travis
        - POSTGRES_PASS=
        - POSTGRES_DATABASE=dqo
        - MYSQL_HOST=127.0.0.1
        - MYSQL_USER=travis
        - MYSQL_PASS=
        - MYSQL_DATABASE=dqo
