services:
    _defaults:
        autowire: true

    database_access_generator.generate_tables:
        class: GW\DQO\Symfony\GenerateTablesCommand
        tags: [{name: console.command}]

    GW\DQO\Generator\TableFactory: ~
    GW\DQO\Generator\Renderer: ~
    GW\DQO\Generator\GenerateTables: ~

    GW\DQO\Formatter\Formatter:
        class: GW\DQO\Formatter\MultiFormatter
        arguments:
            - !service
               class: GW\DQO\Formatter\CsFixerFormatter
            - !service
               class: GW\DQO\Formatter\PhpcbfFormatter
